# Generated by Django 5.2.7 on 2025-12-03 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_remove_admin_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='phone_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='handymanprofile',
            name='phone_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
