# Generated by Django 5.2.7 on 2025-12-13 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_homeownerprofile_delete_customerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='handymanprofile',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Handyman hourly rate in local currency', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='handymanprofile',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='handymanprofile',
            name='is_approved',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='handymanprofile',
            name='is_available',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='handymanprofile',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Handyman base latitude (used for nearby search)', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='handymanprofile',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Handyman base longitude (used for nearby search)', max_digits=9, null=True),
        ),
    ]
