# Generated by Django 5.2.7 on 2025-12-13 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_handymanprofile_hourly_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='handymanprofile',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Profile avatar image', null=True, upload_to='handyman/avatars/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='homeownerprofile',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Profile avatar image', null=True, upload_to='homeowner/avatars/%Y/%m/'),
        ),
    ]
