# Generated by Django 5.2.7 on 2025-12-24 06:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_add_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='HandymanCategory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name_plural': 'Handyman Categories',
                'db_table': 'handyman_categories',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='handymanprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='handymanprofile',
            name='id_number',
            field=models.CharField(blank=True, help_text='National ID number (for future verification)', max_length=50),
        ),
        migrations.AddField(
            model_name='handymanprofile',
            name='job_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='homeownerprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='handymanprofile',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handymen', to='profiles.handymancategory'),
        ),
    ]
