# Generated by Django 5.2.7 on 2026-01-06 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_handymancategory_handymanprofile_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='handymanprofile',
            name='review_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='homeownerprofile',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='homeownerprofile',
            name='review_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
