# Generated by Django 5.2.7 on 2026-04-06 04:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0027_jobapplication_discount_applied_and_more'),
        ('profiles', '0008_handymanprofile_review_count_homeownerprofile_rating_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestLocationSnapshot',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('device_token', models.CharField(max_length=255, unique=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('current_city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guest_location_snapshots', to='jobs.city')),
            ],
            options={
                'db_table': 'guest_location_snapshots',
                'ordering': ['-updated_at'],
            },
        ),
    ]
