# Generated by Django 5.2.7 on 2025-12-06 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_customerprofile_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('handyman', 'Handyman'), ('homeowner', 'Homeowner')], max_length=20),
        ),
    ]
