# Generated by Django 5.2.7 on 2025-12-13 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userrole_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_dummy',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
