# Generated by Django 5.2.7 on 2025-12-06 12:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_add_postal_code_to_job'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='job',
            name='jobs_custome_d3929b_idx',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='customer',
            new_name='homeowner',
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['homeowner'], name='jobs_homeown_1c028b_idx'),
        ),
    ]
