# Generated by Django 5.2.7 on 2025-12-06 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_remove_job_jobs_custome_d3929b_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_items',
            field=models.JSONField(blank=True, default=list, help_text='List of tasks/items to be done for this job'),
        ),
    ]
