# Generated by Django 5.2.7 on 2025-12-10 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_job_job_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='status_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when status was last changed', null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('deleted', 'Deleted')], default='draft', max_length=20),
        ),
    ]
