# Generated by Django 5.2.7 on 2025-12-13 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_add_status_at_to_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_dummy',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
