# Generated by Django 5.2.7 on 2025-12-26 16:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_jobapplication'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='assigned_handyman',
            field=models.ForeignKey(blank=True, help_text='The handyman assigned to this job', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='job',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='completion_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('in_progress', 'In Progress'), ('pending_completion', 'Pending Completion'), ('completed', 'Completed'), ('disputed', 'Disputed'), ('cancelled', 'Cancelled'), ('deleted', 'Deleted')], default='draft', max_length=20),
        ),
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('report_date', models.DateField()),
                ('summary', models.TextField(help_text='Description of work done today')),
                ('total_work_duration', models.DurationField(help_text='Total work duration for this day')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('homeowner_comment', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_deadline', models.DateTimeField()),
                ('handyman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_reports_submitted', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_reports', to='jobs.job')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_reports_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily Report',
                'verbose_name_plural': 'Daily Reports',
                'db_table': 'daily_reports',
                'ordering': ['-report_date'],
            },
        ),
        migrations.CreateModel(
            name='JobDispute',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending Admin Review'), ('in_review', 'Under Review'), ('resolved_full_refund', 'Resolved - Full Refund'), ('resolved_partial_refund', 'Resolved - Partial Refund'), ('resolved_pay_handyman', 'Resolved - Pay Handyman'), ('cancelled', 'Cancelled')], default='pending', max_length=30)),
                ('admin_notes', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('refund_percentage', models.PositiveIntegerField(blank=True, help_text='Refund percentage (0-100)', null=True)),
                ('resolution_deadline', models.DateTimeField()),
                ('disputed_reports', models.ManyToManyField(blank=True, related_name='disputes', to='jobs.dailyreport')),
                ('initiated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes_initiated', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='jobs.job')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disputes_resolved', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job Dispute',
                'verbose_name_plural': 'Job Disputes',
                'db_table': 'job_disputes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobTask',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_tasks', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='jobs.job')),
            ],
            options={
                'verbose_name': 'Job Task',
                'verbose_name_plural': 'Job Tasks',
                'db_table': 'job_tasks',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyReportTask',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('notes', models.TextField(blank=True, help_text='Notes about this task')),
                ('marked_complete', models.BooleanField(default=False, help_text='Handyman marked this task as complete')),
                ('daily_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks_worked', to='jobs.dailyreport')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_report_entries', to='jobs.jobtask')),
            ],
            options={
                'verbose_name': 'Daily Report Task',
                'verbose_name_plural': 'Daily Report Tasks',
                'db_table': 'daily_report_tasks',
                'ordering': ['task__order'],
            },
        ),
        migrations.CreateModel(
            name='WorkSession',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('start_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('start_longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('start_accuracy', models.FloatField(blank=True, null=True)),
                ('start_photo', models.ImageField(upload_to='work-sessions/start-photos/%Y/%m/%d/')),
                ('end_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('end_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('end_accuracy', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed')], default='in_progress', max_length=20)),
                ('handyman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_sessions', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_sessions', to='jobs.job')),
            ],
            options={
                'verbose_name': 'Work Session',
                'verbose_name_plural': 'Work Sessions',
                'db_table': 'work_sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkSessionMedia',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('media_type', models.CharField(choices=[('photo', 'Photo'), ('video', 'Video')], max_length=10)),
                ('file', models.FileField(upload_to='work-sessions/media/%Y/%m/%d/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='work-sessions/thumbnails/%Y/%m/%d/')),
                ('description', models.TextField(blank=True)),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('duration_seconds', models.PositiveIntegerField(blank=True, help_text='Duration for videos', null=True)),
                ('task', models.ForeignKey(blank=True, help_text='Optional: Link to specific task', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media', to='jobs.jobtask')),
                ('work_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='jobs.worksession')),
            ],
            options={
                'verbose_name': 'Work Session Media',
                'verbose_name_plural': 'Work Session Media',
                'db_table': 'work_session_media',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='dailyreport',
            index=models.Index(fields=['job'], name='daily_repor_job_id_219bf1_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyreport',
            index=models.Index(fields=['handyman'], name='daily_repor_handyma_f8c701_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyreport',
            index=models.Index(fields=['status'], name='daily_repor_status_27253c_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyreport',
            index=models.Index(fields=['-report_date'], name='daily_repor_report__469c17_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyreport',
            index=models.Index(fields=['review_deadline'], name='daily_repor_review__a4adb5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyreport',
            unique_together={('job', 'report_date')},
        ),
        migrations.AddIndex(
            model_name='jobdispute',
            index=models.Index(fields=['job'], name='job_dispute_job_id_987d29_idx'),
        ),
        migrations.AddIndex(
            model_name='jobdispute',
            index=models.Index(fields=['status'], name='job_dispute_status_86d2c0_idx'),
        ),
        migrations.AddIndex(
            model_name='jobdispute',
            index=models.Index(fields=['resolution_deadline'], name='job_dispute_resolut_6cf438_idx'),
        ),
        migrations.AddIndex(
            model_name='jobtask',
            index=models.Index(fields=['job'], name='job_tasks_job_id_1e1ba6_idx'),
        ),
        migrations.AddIndex(
            model_name='jobtask',
            index=models.Index(fields=['is_completed'], name='job_tasks_is_comp_9be781_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyreporttask',
            unique_together={('daily_report', 'task')},
        ),
        migrations.AddIndex(
            model_name='worksession',
            index=models.Index(fields=['job'], name='work_sessio_job_id_9ef29c_idx'),
        ),
        migrations.AddIndex(
            model_name='worksession',
            index=models.Index(fields=['handyman'], name='work_sessio_handyma_8c507d_idx'),
        ),
        migrations.AddIndex(
            model_name='worksession',
            index=models.Index(fields=['status'], name='work_sessio_status_7c51a2_idx'),
        ),
        migrations.AddIndex(
            model_name='worksession',
            index=models.Index(fields=['-started_at'], name='work_sessio_started_7e81ea_idx'),
        ),
        migrations.AddIndex(
            model_name='worksessionmedia',
            index=models.Index(fields=['work_session'], name='work_sessio_work_se_d86b14_idx'),
        ),
        migrations.AddIndex(
            model_name='worksessionmedia',
            index=models.Index(fields=['media_type'], name='work_sessio_media_t_201012_idx'),
        ),
    ]
