# Generated by Django 5.2.7 on 2025-12-27 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_migrate_job_items_to_jobtask'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobdispute',
            options={'ordering': ['-created_at'], 'permissions': [('can_manage_disputes', 'Can resolve and manage job disputes')], 'verbose_name': 'Job Dispute', 'verbose_name_plural': 'Job Disputes'},
        ),
    ]
