# Generated by Django 5.2.7 on 2025-12-28 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_add_dispute_management_permission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='job_items',
        ),
    ]
