# Generated by Django 5.2.7 on 2026-01-06 13:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_remove_job_items_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('reviewer_type', models.CharField(choices=[('homeowner', 'Homeowner'), ('handyman', 'Handyman')], max_length=20)),
                ('rating', models.PositiveSmallIntegerField(help_text='Rating from 1 to 5 stars')),
                ('comment', models.TextField(blank=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='jobs.job')),
                ('reviewee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'db_table': 'reviews',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['job'], name='reviews_job_id_ba04c2_idx'), models.Index(fields=['reviewer'], name='reviews_reviewe_965d53_idx'), models.Index(fields=['reviewee'], name='reviews_reviewe_0d427f_idx'), models.Index(fields=['reviewer_type'], name='reviews_reviewe_07cb7e_idx')],
                'unique_together': {('job', 'reviewer_type')},
            },
        ),
    ]
