# Generated by Django 5.2.7 on 2026-01-07 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksession',
            name='end_latitude',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='worksession',
            name='end_longitude',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='worksession',
            name='start_latitude',
            field=models.DecimalField(decimal_places=9, max_digits=12),
        ),
        migrations.AlterField(
            model_name='worksession',
            name='start_longitude',
            field=models.DecimalField(decimal_places=9, max_digits=12),
        ),
    ]
