# Generated by Django 5.2.7 on 2026-01-07 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0014_alter_worksession_end_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksession',
            name='end_photo',
            field=models.ImageField(blank=True, null=True, upload_to='work-sessions/end-photos/%Y/%m/%d/'),
        ),
    ]
