# Generated by Django 5.2.7 on 2026-01-11 05:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0015_add_end_photo_to_worksession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='estimated_total_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Estimated total price from handyman (labor + material)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='negotiation_reasoning',
            field=models.TextField(blank=True, help_text='Detailed reasoning of negotiation'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='predicted_hours',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Predicted total hours needed', max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='JobApplicationAttachment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('file', models.FileField(upload_to='job-applications/attachments/%Y/%m/%d/')),
                ('file_name', models.CharField(help_text='Original file name', max_length=255)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='jobs.jobapplication')),
            ],
            options={
                'verbose_name': 'Job Application Attachment',
                'verbose_name_plural': 'Job Application Attachments',
                'db_table': 'job_application_attachments',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['application'], name='job_applica_applica_8c22fb_idx')],
            },
        ),
        migrations.CreateModel(
            name='JobApplicationMaterial',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(help_text='Material name', max_length=255)),
                ('price', models.DecimalField(decimal_places=2, help_text='Material price', max_digits=10)),
                ('description', models.CharField(blank=True, help_text="Description/quantity (e.g., '2m', '2kg')", max_length=255)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='jobs.jobapplication')),
            ],
            options={
                'verbose_name': 'Job Application Material',
                'verbose_name_plural': 'Job Application Materials',
                'db_table': 'job_application_materials',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['application'], name='job_applica_applica_5a8818_idx')],
            },
        ),
        migrations.CreateModel(
            name='JobReimbursement',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(help_text='Name/title of the expense', max_length=255)),
                ('category', models.CharField(choices=[('materials', 'Materials'), ('tools', 'Tools'), ('transport', 'Transportation'), ('equipment', 'Equipment Rental'), ('other', 'Other')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Reimbursement amount', max_digits=10)),
                ('attachment', models.FileField(upload_to='reimbursements/attachments/%Y/%m/%d/')),
                ('notes', models.TextField(blank=True, help_text='Optional description/notes')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('homeowner_comment', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('handyman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reimbursements_submitted', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reimbursements', to='jobs.job')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reimbursements_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job Reimbursement',
                'verbose_name_plural': 'Job Reimbursements',
                'db_table': 'job_reimbursements',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['job'], name='job_reimbur_job_id_ccec82_idx'), models.Index(fields=['handyman'], name='job_reimbur_handyma_52d67d_idx'), models.Index(fields=['status'], name='job_reimbur_status_bb88b2_idx'), models.Index(fields=['-created_at'], name='job_reimbur_created_18c215_idx')],
            },
        ),
    ]
