# Generated by Django 5.2.7 on 2026-01-11 09:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0016_jobapplication_estimated_total_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobreimbursement',
            name='attachment',
        ),
        migrations.CreateModel(
            name='JobReimbursementAttachment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('file', models.FileField(upload_to='reimbursements/attachments/%Y/%m/%d/')),
                ('file_name', models.CharField(help_text='Original file name', max_length=255)),
                ('reimbursement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='jobs.jobreimbursement')),
            ],
            options={
                'verbose_name': 'Job Reimbursement Attachment',
                'verbose_name_plural': 'Job Reimbursement Attachments',
                'db_table': 'job_reimbursement_attachments',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['reimbursement'], name='job_reimbur_reimbur_de225f_idx')],
            },
        ),
    ]
