# Generated by Django 5.2.7 on 2026-01-11 11:38

import uuid

import django.db.models.deletion
from django.db import migrations, models


def create_initial_categories(apps, schema_editor):
    """Create initial reimbursement categories from the old CATEGORY_CHOICES."""
    JobReimbursementCategory = apps.get_model("jobs", "JobReimbursementCategory")

    categories = [
        {
            "name": "Materials",
            "slug": "materials",
            "description": "Building materials and supplies",
            "icon": "materials",
        },
        {
            "name": "Tools",
            "slug": "tools",
            "description": "Tools and equipment",
            "icon": "tools",
        },
        {
            "name": "Transportation",
            "slug": "transport",
            "description": "Transportation and travel expenses",
            "icon": "transport",
        },
        {
            "name": "Equipment Rental",
            "slug": "equipment",
            "description": "Equipment rental costs",
            "icon": "equipment",
        },
        {
            "name": "Other",
            "slug": "other",
            "description": "Other miscellaneous expenses",
            "icon": "other",
        },
    ]

    for cat_data in categories:
        JobReimbursementCategory.objects.get_or_create(
            slug=cat_data["slug"],
            defaults={
                "name": cat_data["name"],
                "description": cat_data["description"],
                "icon": cat_data["icon"],
                "is_active": True,
            },
        )


def reverse_categories(apps, schema_editor):
    """Reverse migration - delete all categories."""
    JobReimbursementCategory = apps.get_model("jobs", "JobReimbursementCategory")
    JobReimbursementCategory.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0017_update_jobreimbursement_add_attachment_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobReimbursementCategory",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("icon", models.CharField(blank=True, max_length=50)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Job Reimbursement Category",
                "verbose_name_plural": "Job Reimbursement Categories",
                "db_table": "job_reimbursement_categories",
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["is_active"], name="job_reimbur_is_acti_1826e4_idx"
                    ),
                    models.Index(fields=["slug"], name="job_reimbur_slug_23ed61_idx"),
                ],
            },
        ),
        # Create initial categories first
        migrations.RunPython(create_initial_categories, reverse_categories),
        # Then alter the field to FK
        migrations.AlterField(
            model_name="jobreimbursement",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reimbursements",
                to="jobs.jobreimbursementcategory",
            ),
        ),
    ]
