# Generated by Django 5.2.7

from django.db import migrations, models


def migrate_jobimage_to_jobattachment(apps, schema_editor):
    """
    Migrate data from job_images to job_attachments.
    All existing records are images, so set defaults accordingly.
    """
    JobAttachment = apps.get_model("jobs", "JobAttachment")

    # Update all existing records with image defaults
    JobAttachment.objects.all().update(
        file_type="image",
        file_name="",
        file_size=0,
    )


def reverse_migrate(apps, schema_editor):
    """
    Reverse migration - no action needed as we're just updating fields.
    """
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0018_add_job_reimbursement_category"),
    ]

    operations = [
        # Step 1: Rename the model from JobImage to JobAttachment
        migrations.RenameModel(
            old_name="JobImage",
            new_name="JobAttachment",
        ),
        # Step 2: Rename the table from job_images to job_attachments
        migrations.AlterModelTable(
            name="jobattachment",
            table="job_attachments",
        ),
        # Step 3: Rename 'image' field to 'file'
        migrations.RenameField(
            model_name="jobattachment",
            old_name="image",
            new_name="file",
        ),
        # Step 4: Add new fields
        migrations.AddField(
            model_name="jobattachment",
            name="file_type",
            field=models.CharField(
                choices=[("image", "Image"), ("video", "Video")],
                default="image",
                max_length=10,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="jobattachment",
            name="file_name",
            field=models.CharField(
                default="",
                help_text="Original file name",
                max_length=255,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="jobattachment",
            name="file_size",
            field=models.PositiveIntegerField(
                default=0,
                help_text="File size in bytes",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="jobattachment",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                help_text="Thumbnail for video attachments",
                null=True,
                upload_to="jobs/thumbnails/%Y/%m/%d/",
            ),
        ),
        migrations.AddField(
            model_name="jobattachment",
            name="duration_seconds",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Duration in seconds for video attachments",
                null=True,
            ),
        ),
        # Step 5: Update the file field to use FileField instead of ImageField
        migrations.AlterField(
            model_name="jobattachment",
            name="file",
            field=models.FileField(upload_to="jobs/attachments/%Y/%m/%d/"),
        ),
        # Step 6: Remove the unique_together constraint (no longer needed)
        migrations.AlterUniqueTogether(
            name="jobattachment",
            unique_together=set(),
        ),
        # Step 7: Add new indexes
        migrations.AddIndex(
            model_name="jobattachment",
            index=models.Index(fields=["file_type"], name="job_attachm_file_ty_idx"),
        ),
        # Step 8: Update model options
        migrations.AlterModelOptions(
            name="jobattachment",
            options={
                "ordering": ["order", "created_at"],
                "verbose_name": "Job Attachment",
                "verbose_name_plural": "Job Attachments",
            },
        ),
        # Step 9: Run data migration
        migrations.RunPython(migrate_jobimage_to_jobattachment, reverse_migrate),
    ]
