# Generated by Django 5.2.7 on 2026-01-14 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0019_jobimage_to_jobattachment'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='jobattachment',
            new_name='job_attachm_job_id_99494d_idx',
            old_name='job_images_job_id_10e2bc_idx',
        ),
        migrations.RenameIndex(
            model_name='jobattachment',
            new_name='job_attachm_order_fef295_idx',
            old_name='job_images_order_7fd2c7_idx',
        ),
        migrations.RenameIndex(
            model_name='jobattachment',
            new_name='job_attachm_file_ty_9a3e13_idx',
            old_name='job_attachm_file_ty_idx',
        ),
        migrations.AddField(
            model_name='jobapplicationattachment',
            name='duration_seconds',
            field=models.PositiveIntegerField(blank=True, help_text='Duration in seconds for video attachments', null=True),
        ),
        migrations.AddField(
            model_name='jobapplicationattachment',
            name='file_size',
            field=models.PositiveIntegerField(default=0, help_text='File size in bytes'),
        ),
        migrations.AddField(
            model_name='jobapplicationattachment',
            name='file_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10),
        ),
        migrations.AddField(
            model_name='jobapplicationattachment',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Thumbnail for video attachments', null=True, upload_to='job-applications/thumbnails/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='jobreimbursementattachment',
            name='duration_seconds',
            field=models.PositiveIntegerField(blank=True, help_text='Duration in seconds for video attachments', null=True),
        ),
        migrations.AddField(
            model_name='jobreimbursementattachment',
            name='file_size',
            field=models.PositiveIntegerField(default=0, help_text='File size in bytes'),
        ),
        migrations.AddField(
            model_name='jobreimbursementattachment',
            name='file_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10),
        ),
        migrations.AddField(
            model_name='jobreimbursementattachment',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Thumbnail for video attachments', null=True, upload_to='reimbursements/thumbnails/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='jobattachment',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='jobs.job'),
        ),
        migrations.AddIndex(
            model_name='jobapplicationattachment',
            index=models.Index(fields=['file_type'], name='job_applica_file_ty_4e2c79_idx'),
        ),
        migrations.AddIndex(
            model_name='jobreimbursementattachment',
            index=models.Index(fields=['file_type'], name='job_reimbur_file_ty_d76400_idx'),
        ),
    ]
