# Generated by Django 5.2.7 on 2026-01-16 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0020_rename_job_images_job_id_10e2bc_idx_job_attachm_job_id_99494d_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplicationattachment',
            name='file_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('document', 'Document')], default='image', max_length=10),
        ),
        migrations.AlterField(
            model_name='jobreimbursementattachment',
            name='file_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('document', 'Document')], default='image', max_length=10),
        ),
    ]
