# Generated by Django 5.2.7 on 2026-01-16 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0021_add_document_file_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_direct_offer',
            field=models.BooleanField(db_index=True, default=False, help_text='True if this job is a direct offer to a specific handyman'),
        ),
        migrations.AddField(
            model_name='job',
            name='offer_expires_at',
            field=models.DateTimeField(blank=True, help_text='When the direct offer expires', null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='offer_rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection (optional, from handyman)'),
        ),
        migrations.AddField(
            model_name='job',
            name='offer_responded_at',
            field=models.DateTimeField(blank=True, help_text='When the handyman responded to the offer', null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='offer_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('converted', 'Converted to Public')], help_text='Status of the direct offer', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='target_handyman',
            field=models.ForeignKey(blank=True, help_text='Target handyman for direct offers', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_job_offers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['is_direct_offer'], name='jobs_is_dire_d0c572_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['target_handyman'], name='jobs_target__d26d15_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['offer_status'], name='jobs_offer_s_92f43a_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['offer_expires_at'], name='jobs_offer_e_65d223_idx'),
        ),
    ]
