# Generated by Django 5.2.7 on 2026-01-17 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0022_add_direct_offer_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='postal_code',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
