# Generated by Django 5.2.7 on 2026-02-19 15:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0023_alter_job_postal_code_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='payment_mode',
            field=models.CharField(choices=[('legacy_exempt', 'Legacy Exempt'), ('stripe_required', 'Stripe Required')], db_index=True, default='stripe_required', help_text='Controls whether Stripe-managed payment flow is required.', max_length=20),
        ),
        migrations.AddField(
            model_name='jobdispute',
            name='financial_action_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobdispute',
            name='financial_action_status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('success', 'Success'), ('failed', 'Failed'), ('legacy_exempt', 'Legacy Exempt')], default='not_started', max_length=30),
        ),
        migrations.AddField(
            model_name='jobdispute',
            name='financial_outcome_amount_cents',
            field=models.IntegerField(blank=True, help_text='Final financial outcome amount in cents after dispute resolution. Positive values indicate payout/capture, negative values indicate refund.', null=True),
        ),
        migrations.AlterField(
            model_name='worksession',
            name='start_photo',
            field=models.ImageField(blank=True, null=True, upload_to='work-sessions/start-photos/%Y/%m/%d/'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['payment_mode'], name='jobs_payment_1557d8_idx'),
        ),
        migrations.AddIndex(
            model_name='jobdispute',
            index=models.Index(fields=['financial_action_status'], name='job_dispute_financi_c3858c_idx'),
        ),
    ]
