# Generated by Django 5.2.7 on 2026-02-26 02:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0001_initial'),
        ('jobs', '0025_backfill_job_payment_mode_legacy_exempt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='discount',
            field=models.ForeignKey(blank=True, help_text='Discount applied to this job', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='discounts.discount'),
        ),
        migrations.AddField(
            model_name='job',
            name='platform_fee_discount_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Platform fee discount percentage applied to this job', max_digits=5, null=True),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['discount'], name='jobs_discoun_32e939_idx'),
        ),
    ]
