# Generated by Django 5.2.7 on 2026-02-26 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0026_job_discount_job_platform_fee_discount_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='discount_applied',
            field=models.BooleanField(default=False, help_text='Whether the discount has been applied to the job'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='discount_code',
            field=models.CharField(blank=True, help_text='Discount code used by handyman (applied when job is assigned)', max_length=50),
        ),
    ]
