from django.urls import path

from ..views import mobile as mobile_views

urlpatterns = [
    # Supporting endpoints (no role required)
    path(
        "job-categories/",
        mobile_views.JobCategoryListView.as_view(),
        name="mobile_job_categories",
    ),
    path(
        "cities/",
        mobile_views.CityListView.as_view(),
        name="mobile_cities",
    ),
    # Homeowner job endpoints
    path(
        "homeowner/jobs/",
        mobile_views.JobListCreateView.as_view(),
        name="mobile_homeowner_jobs",
    ),
    path(
        "homeowner/jobs/for-you/",
        mobile_views.ForYouJobListView.as_view(),
        name="mobile_homeowner_jobs_for_you",
    ),
    path(
        "homeowner/jobs/<uuid:public_id>/",
        mobile_views.JobDetailView.as_view(),
        name="mobile_homeowner_job_detail",
    ),
    # Guest job endpoints (no authentication required)
    path(
        "guest/jobs/",
        mobile_views.GuestJobListView.as_view(),
        name="mobile_guest_jobs",
    ),
    path(
        "guest/jobs/<uuid:public_id>/",
        mobile_views.GuestJobDetailView.as_view(),
        name="mobile_guest_job_detail",
    ),
    # Handyman job browsing endpoints
    path(
        "handyman/jobs/for-you/",
        mobile_views.HandymanForYouJobListView.as_view(),
        name="mobile_handyman_jobs_for_you",
    ),
    path(
        "handyman/jobs/<uuid:public_id>/",
        mobile_views.HandymanJobDetailView.as_view(),
        name="mobile_handyman_job_detail",
    ),
    # Handyman application endpoints
    path(
        "handyman/applications/",
        mobile_views.HandymanJobApplicationListCreateView.as_view(),
        name="mobile_handyman_applications",
    ),
    path(
        "handyman/applications/<uuid:public_id>/",
        mobile_views.HandymanJobApplicationDetailView.as_view(),
        name="mobile_handyman_application_detail",
    ),
    path(
        "handyman/applications/<uuid:public_id>/withdraw/",
        mobile_views.HandymanJobApplicationWithdrawView.as_view(),
        name="mobile_handyman_application_withdraw",
    ),
    # Homeowner application management endpoints (global)
    path(
        "homeowner/applications/",
        mobile_views.HomeownerApplicationListView.as_view(),
        name="mobile_homeowner_applications",
    ),
    path(
        "homeowner/applications/<uuid:public_id>/",
        mobile_views.HomeownerApplicationDetailView.as_view(),
        name="mobile_homeowner_application_detail",
    ),
    path(
        "homeowner/applications/<uuid:public_id>/approve/",
        mobile_views.HomeownerApplicationApproveView.as_view(),
        name="mobile_homeowner_application_approve",
    ),
    path(
        "homeowner/applications/<uuid:public_id>/reject/",
        mobile_views.HomeownerApplicationRejectView.as_view(),
        name="mobile_homeowner_application_reject",
    ),
    # Homeowner Ongoing Job Endpoints (Read)
    path(
        "homeowner/jobs/<uuid:public_id>/sessions/",
        mobile_views.HomeownerWorkSessionListView.as_view(),
        name="mobile_homeowner_jobs_sessions_list",
    ),
    path(
        "homeowner/jobs/<uuid:public_id>/sessions/<uuid:session_id>/",
        mobile_views.HomeownerWorkSessionDetailView.as_view(),
        name="mobile_homeowner_jobs_sessions_detail",
    ),
    path(
        "homeowner/jobs/<uuid:public_id>/reports/",
        mobile_views.HomeownerDailyReportListView.as_view(),
        name="mobile_homeowner_jobs_reports_list",
    ),
    path(
        "homeowner/jobs/<uuid:public_id>/reports/<uuid:report_id>/",
        mobile_views.HomeownerDailyReportDetailView.as_view(),
        name="mobile_homeowner_jobs_reports_detail",
    ),
    path(
        "homeowner/jobs/<uuid:public_id>/disputes/",
        mobile_views.HomeownerJobDisputeListView.as_view(),
        name="mobile_homeowner_jobs_disputes_list",
    ),
    # Homeowner Ongoing Job Endpoints (Write)
    path(
        "homeowner/jobs/<uuid:public_id>/reports/<uuid:report_id>/review/",
        mobile_views.HomeownerDailyReportReviewView.as_view(),
        name="mobile_homeowner_jobs_reports_review",
    ),
    path(
        "homeowner/jobs/<uuid:public_id>/completion/approve/",
        mobile_views.HomeownerCompletionApproveView.as_view(),
        name="mobile_homeowner_jobs_completion_approve",
    ),
    path(
        "homeowner/jobs/<uuid:public_id>/completion/reject/",
        mobile_views.HomeownerCompletionRejectView.as_view(),
        name="mobile_homeowner_jobs_completion_reject",
    ),
    path(
        "homeowner/jobs/<uuid:public_id>/disputes/create/",
        mobile_views.HomeownerDisputeCreateView.as_view(),
        name="mobile_homeowner_jobs_disputes_create",
    ),
    # Handyman Ongoing Job Endpoints (Read)
    path(
        "handyman/jobs/<uuid:public_id>/sessions/",
        mobile_views.HandymanWorkSessionListView.as_view(),
        name="mobile_handyman_jobs_sessions_list",
    ),
    path(
        "handyman/jobs/<uuid:public_id>/sessions/<uuid:session_id>/",
        mobile_views.HandymanWorkSessionDetailView.as_view(),
        name="mobile_handyman_jobs_sessions_detail",
    ),
    path(
        "handyman/jobs/<uuid:public_id>/reports/",
        mobile_views.HandymanDailyReportListView.as_view(),
        name="mobile_handyman_jobs_reports_list",
    ),
    path(
        "handyman/jobs/<uuid:public_id>/reports/<uuid:report_id>/",
        mobile_views.HandymanDailyReportDetailView.as_view(),
        name="mobile_handyman_jobs_reports_detail",
    ),
    path(
        "handyman/jobs/<uuid:public_id>/reports/<uuid:report_id>/edit/",
        mobile_views.HandymanDailyReportEditView.as_view(),
        name="mobile_handyman_jobs_reports_update",
    ),
    path(
        "handyman/jobs/<uuid:public_id>/disputes/",
        mobile_views.HandymanJobDisputeListView.as_view(),
        name="mobile_handyman_jobs_disputes_list",
    ),
    # Handyman Ongoing Job Endpoints (Write)
    path(
        "handyman/jobs/<uuid:public_id>/sessions/start/",
        mobile_views.HandymanWorkSessionStartView.as_view(),
        name="mobile_handyman_jobs_sessions_start",
    ),
    path(
        "handyman/jobs/<uuid:public_id>/sessions/<uuid:session_id>/stop/",
        mobile_views.HandymanWorkSessionStopView.as_view(),
        name="mobile_handyman_jobs_sessions_stop",
    ),
    path(
        "handyman/jobs/<uuid:public_id>/sessions/<uuid:session_id>/media/",
        mobile_views.HandymanWorkSessionMediaUploadView.as_view(),
        name="mobile_handyman_jobs_sessions_media",
    ),
    path(
        "handyman/jobs/<uuid:public_id>/reports/create/",
        mobile_views.HandymanDailyReportCreateView.as_view(),
        name="mobile_handyman_jobs_reports_create",
    ),
    path(
        "handyman/jobs/<uuid:public_id>/completion/request/",
        mobile_views.HandymanCompletionRequestView.as_view(),
        name="mobile_handyman_jobs_completion_request",
    ),
    path(
        "handyman/jobs/<uuid:public_id>/tasks/<uuid:task_id>/status/",
        mobile_views.HandymanJobTaskStatusView.as_view(),
        name="mobile_handyman_jobs_tasks_status_update",
    ),
]
