# Generated by Django 5.2.7 on 2026-02-19 15:46

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0024_job_payment_mode_jobdispute_financial_action_error_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeConnectedAccount',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('stripe_account_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('account_type', models.CharField(choices=[('express', 'Express'), ('custom', 'Custom'), ('standard', 'Standard')], default='express', max_length=20)),
                ('charges_enabled', models.BooleanField(default=False)),
                ('payouts_enabled', models.BooleanField(default=False)),
                ('details_submitted', models.BooleanField(default=False)),
                ('requirements_due', models.JSONField(blank=True, default=list)),
                ('disabled_reason', models.CharField(blank=True, max_length=255)),
                ('onboarding_completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stripe_connected_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Stripe Connected Account',
                'verbose_name_plural': 'Stripe Connected Accounts',
                'db_table': 'stripe_connected_accounts',
            },
        ),
        migrations.CreateModel(
            name='StripeCustomerProfile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('stripe_customer_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('currency', models.CharField(default='cad', max_length=3)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stripe_customer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Stripe Customer Profile',
                'verbose_name_plural': 'Stripe Customer Profiles',
                'db_table': 'stripe_customer_profiles',
            },
        ),
        migrations.CreateModel(
            name='JobPayment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('payment_intent_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('currency', models.CharField(default='cad', max_length=3)),
                ('service_amount_cents', models.PositiveIntegerField(default=0)),
                ('reimbursement_approved_cents', models.PositiveIntegerField(default=0)),
                ('reserve_cents', models.PositiveIntegerField(default=0)),
                ('authorized_amount_cents', models.PositiveIntegerField(default=0)),
                ('capturable_amount_cents', models.PositiveIntegerField(default=0)),
                ('captured_amount_cents', models.PositiveIntegerField(default=0)),
                ('platform_fee_cents', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('requires_payment_method', 'Requires Payment Method'), ('requires_confirmation', 'Requires Confirmation'), ('authorized', 'Authorized'), ('captured', 'Captured'), ('canceled', 'Canceled'), ('failed', 'Failed'), ('partially_refunded', 'Partially Refunded'), ('refunded', 'Refunded'), ('disputed', 'Disputed')], default='draft', max_length=40)),
                ('last_failure_code', models.CharField(blank=True, max_length=100)),
                ('last_failure_message', models.TextField(blank=True)),
                ('authorized_at', models.DateTimeField(blank=True, null=True)),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='jobs.job')),
                ('connected_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_payments', to='payments.stripeconnectedaccount')),
                ('customer_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_payments', to='payments.stripecustomerprofile')),
            ],
            options={
                'verbose_name': 'Job Payment',
                'verbose_name_plural': 'Job Payments',
                'db_table': 'job_payments',
            },
        ),
        migrations.CreateModel(
            name='StripeEventLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('stripe_event_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('event_type', models.CharField(db_index=True, max_length=150)),
                ('payload_json', models.JSONField(default=dict)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Stripe Event Log',
                'verbose_name_plural': 'Stripe Event Logs',
                'db_table': 'stripe_event_logs',
                'indexes': [models.Index(fields=['stripe_event_id'], name='stripe_even_stripe__8da3f7_idx'), models.Index(fields=['event_type', 'processing_status'], name='stripe_even_event_t_1ef878_idx')],
            },
        ),
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('amount_cents', models.PositiveIntegerField()),
                ('currency', models.CharField(default='cad', max_length=3)),
                ('method', models.CharField(choices=[('standard', 'Standard'), ('instant', 'Instant')], default='standard', max_length=20)),
                ('instant_fee_cents', models.PositiveIntegerField(default=0)),
                ('stripe_payout_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('processing', 'Processing'), ('paid', 'Paid'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='requested', max_length=20)),
                ('failure_code', models.CharField(blank=True, max_length=100)),
                ('failure_message', models.TextField(blank=True)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('connected_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='withdrawal_requests', to='payments.stripeconnectedaccount')),
                ('handyman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Withdrawal Request',
                'verbose_name_plural': 'Withdrawal Requests',
                'db_table': 'withdrawal_requests',
            },
        ),
        migrations.CreateModel(
            name='HandymanIdentityVerification',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('verification_session_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('requires_input', 'Requires Input'), ('failed', 'Failed')], default='pending', max_length=30)),
                ('last_error_code', models.CharField(blank=True, max_length=100)),
                ('last_error_reason', models.TextField(blank=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='identity_verification', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Handyman Identity Verification',
                'verbose_name_plural': 'Handyman Identity Verifications',
                'db_table': 'handyman_identity_verifications',
                'indexes': [models.Index(fields=['verification_session_id'], name='handyman_id_verific_ce6a85_idx'), models.Index(fields=['status'], name='handyman_id_status_52c67b_idx')],
            },
        ),
        migrations.CreateModel(
            name='PaymentRefund',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('stripe_refund_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True)),
                ('amount_cents', models.PositiveIntegerField(default=0)),
                ('reason', models.CharField(blank=True, max_length=100)),
                ('source', models.CharField(choices=[('dispute', 'Dispute'), ('admin', 'Admin'), ('chargeback', 'Chargeback')], default='admin', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='pending', max_length=20)),
                ('failure_reason', models.TextField(blank=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('job_payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='payments.jobpayment')),
            ],
            options={
                'verbose_name': 'Payment Refund',
                'verbose_name_plural': 'Payment Refunds',
                'db_table': 'payment_refunds',
                'indexes': [models.Index(fields=['job_payment'], name='payment_ref_job_pay_98aa77_idx'), models.Index(fields=['source', 'status'], name='payment_ref_source_4a181b_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='stripeconnectedaccount',
            index=models.Index(fields=['stripe_account_id'], name='stripe_conn_stripe__42857c_idx'),
        ),
        migrations.AddIndex(
            model_name='stripeconnectedaccount',
            index=models.Index(fields=['charges_enabled', 'payouts_enabled'], name='stripe_conn_charges_a7bb68_idx'),
        ),
        migrations.AddIndex(
            model_name='stripecustomerprofile',
            index=models.Index(fields=['stripe_customer_id'], name='stripe_cust_stripe__d81f90_idx'),
        ),
        migrations.AddIndex(
            model_name='jobpayment',
            index=models.Index(fields=['payment_intent_id'], name='job_payment_payment_546f99_idx'),
        ),
        migrations.AddIndex(
            model_name='jobpayment',
            index=models.Index(fields=['status'], name='job_payment_status_421d6c_idx'),
        ),
        migrations.AddIndex(
            model_name='jobpayment',
            index=models.Index(fields=['job'], name='job_payment_job_id_d5301c_idx'),
        ),
        migrations.AddIndex(
            model_name='withdrawalrequest',
            index=models.Index(fields=['handyman', 'status'], name='withdrawal__handyma_9f017e_idx'),
        ),
        migrations.AddIndex(
            model_name='withdrawalrequest',
            index=models.Index(fields=['stripe_payout_id'], name='withdrawal__stripe__dd5bf2_idx'),
        ),
    ]
