# Generated by Django 5.2.7 on 2025-12-03 14:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountryPhoneCode',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('country_code', models.CharField(help_text="ISO 3166-1 alpha-2 code (e.g., 'ID', 'CA')", max_length=3, unique=True)),
                ('country_name', models.CharField(max_length=100)),
                ('dial_code', models.CharField(help_text="Dialing code (e.g., '+62')", max_length=10)),
                ('flag_emoji', models.CharField(blank=True, max_length=10)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first')),
            ],
            options={
                'db_table': 'country_phone_codes',
                'ordering': ['display_order', 'country_name'],
            },
        ),
    ]
