# Generated by Django 5.2.7 on 2026-02-26 02:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0025_backfill_job_payment_mode_legacy_exempt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(help_text='Display name for the discount', max_length=100)),
                ('code', models.CharField(help_text='Unique code in ALL CAPS (e.g., FIRST20)', max_length=50, unique=True)),
                ('description', models.TextField(help_text='Marketing description shown to users')),
                ('terms_and_conditions', models.TextField(default='This discount applies to the platform fee only, not the job value.', help_text='Terms and conditions including app cut fee disclaimer')),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed_amount', 'Fixed Amount')], default='percentage', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Percentage (e.g., 20.00 for 20%) or fixed amount', max_digits=10)),
                ('target_role', models.CharField(choices=[('homeowner', 'Homeowner'), ('handyman', 'Handyman'), ('both', 'Both')], default='homeowner', help_text='Who can use this discount', max_length=20)),
                ('start_date', models.DateTimeField(help_text='When discount becomes active')),
                ('end_date', models.DateTimeField(help_text='When discount expires')),
                ('max_uses_global', models.PositiveIntegerField(default=0, help_text='Maximum total uses (0 = unlimited)')),
                ('total_used_count', models.PositiveIntegerField(default=0, help_text='Total times this discount has been used')),
                ('max_uses_per_user', models.PositiveIntegerField(default=1, help_text='Maximum uses per user')),
                ('is_active', models.BooleanField(default=True, help_text='Whether discount is currently active')),
                ('color', models.CharField(default='#0C9A5C', help_text='Hex color code (e.g., #0C9A5C)', max_length=7)),
                ('icon', models.CharField(choices=[('sparkles', 'Sparkles'), ('gift', 'Gift'), ('wrench', 'Wrench'), ('tag', 'Tag'), ('percent', 'Percent'), ('dollar_sign', 'Dollar Sign'), ('star', 'Star'), ('zap', 'Zap')], default='sparkles', help_text='Icon to display on discount card', max_length=20)),
                ('badge_text', models.CharField(blank=True, help_text="Optional badge (e.g., 'POPULAR', 'NEW')", max_length=50)),
            ],
            options={
                'verbose_name': 'Discount',
                'verbose_name_plural': 'Discounts',
                'db_table': 'discounts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['code'], name='discounts_code_74af5d_idx'), models.Index(fields=['target_role'], name='discounts_target__4c3f01_idx'), models.Index(fields=['is_active'], name='discounts_is_acti_49deb3_idx'), models.Index(fields=['start_date', 'end_date'], name='discounts_start_d_a6f943_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserDiscountUsage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('usage_number', models.PositiveIntegerField(default=1, help_text='Which usage number this is for the user (1, 2, 3, etc.)')),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_usages', to='discounts.discount')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discount_usages', to='jobs.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_usages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Discount Usage',
                'verbose_name_plural': 'User Discount Usages',
                'db_table': 'user_discount_usages',
                'ordering': ['-used_at'],
                'indexes': [models.Index(fields=['user', 'discount'], name='user_discou_user_id_22781a_idx'), models.Index(fields=['used_at'], name='user_discou_used_at_93cecb_idx')],
                'unique_together': {('user', 'discount', 'usage_number')},
            },
        ),
    ]
