# Generated by Django 5.2.7 on 2026-01-08 15:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0015_add_end_photo_to_worksession'),
        ('profiles', '0008_handymanprofile_review_count_homeownerprofile_rating_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HandymanBookmark',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('handyman_profile', models.ForeignKey(help_text='The bookmarked handyman profile', on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='profiles.handymanprofile')),
                ('homeowner', models.ForeignKey(help_text='The homeowner who bookmarked the handyman', on_delete=django.db.models.deletion.CASCADE, related_name='handyman_bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Handyman Bookmark',
                'verbose_name_plural': 'Handyman Bookmarks',
                'db_table': 'handyman_bookmarks',
                'ordering': ['-created_at'],
                'unique_together': {('homeowner', 'handyman_profile')},
            },
        ),
        migrations.CreateModel(
            name='JobBookmark',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('handyman', models.ForeignKey(help_text='The handyman who bookmarked the job', on_delete=django.db.models.deletion.CASCADE, related_name='job_bookmarks', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(help_text='The bookmarked job', on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='jobs.job')),
            ],
            options={
                'verbose_name': 'Job Bookmark',
                'verbose_name_plural': 'Job Bookmarks',
                'db_table': 'job_bookmarks',
                'ordering': ['-created_at'],
                'unique_together': {('handyman', 'job')},
            },
        ),
    ]
