# Generated by Django 5.2.7 on 2025-12-18 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authn', '0002_phone_verification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneverificationcode',
            name='phone_number',
            field=models.CharField(db_index=True, max_length=20),
        ),
    ]
