# Generated by Django 5.2.7 on 2025-12-20 15:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('job_application_received', 'Job Application Received'), ('application_approved', 'Application Approved'), ('application_rejected', 'Application Rejected'), ('application_withdrawn', 'Application Withdrawn'), ('admin_broadcast', 'Admin Broadcast')], max_length=50),
        ),
        migrations.CreateModel(
            name='BroadcastNotification',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('data', models.JSONField(blank=True, null=True)),
                ('target_audience', models.CharField(choices=[('all', 'All Users'), ('handyman', 'All Handymen'), ('homeowner', 'All Homeowners')], max_length=20)),
                ('send_push', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('total_recipients', models.PositiveIntegerField(default=0)),
                ('push_success_count', models.PositiveIntegerField(default=0)),
                ('push_failure_count', models.PositiveIntegerField(default=0)),
                ('sent_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'broadcast_notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
