# Generated by Django 5.2.7 on 2025-12-20 15:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_notification_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcastnotification',
            name='target_users',
            field=models.ManyToManyField(blank=True, related_name='targeted_broadcasts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='broadcastnotification',
            name='target_audience',
            field=models.CharField(choices=[('all', 'All Users'), ('handyman', 'All Handymen'), ('homeowner', 'All Homeowners'), ('specific', 'Specific Users')], max_length=20),
        ),
    ]
