# Generated by Django 5.2.7 on 2026-01-06 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_alter_notification_type_add_daily_report_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('job_application_received', 'Job Application Received'), ('application_approved', 'Application Approved'), ('application_rejected', 'Application Rejected'), ('application_withdrawn', 'Application Withdrawn'), ('admin_broadcast', 'Admin Broadcast'), ('work_session_started', 'Work Session Started'), ('work_session_ended', 'Work Session Ended'), ('work_session_media_uploaded', 'Work Session Media Uploaded'), ('daily_report_submitted', 'Daily Report Submitted'), ('daily_report_approved', 'Daily Report Approved'), ('daily_report_rejected', 'Daily Report Rejected'), ('daily_report_updated', 'Daily Report Updated'), ('job_completion_requested', 'Job Completion Requested'), ('job_completion_approved', 'Job Completion Approved'), ('job_completion_rejected', 'Job Completion Rejected'), ('job_dispute_opened', 'Job Dispute Opened'), ('job_dispute_resolved', 'Job Dispute Resolved'), ('review_received', 'Review Received')], max_length=50),
        ),
    ]
