# Generated by Django 5.2.7

from django.db import migrations, models


def migrate_chatmessageimage_to_attachment(apps, schema_editor):
    """
    Migrate data from chat_message_images to chat_message_attachments.
    All existing records are images, so set defaults accordingly.
    """
    ChatMessageAttachment = apps.get_model("chat", "ChatMessageAttachment")

    # Update all existing records with image defaults
    ChatMessageAttachment.objects.all().update(
        file_type="image",
        file_name="",
        file_size=0,
    )


def update_message_types(apps, schema_editor):
    """
    Update ChatMessage message_type values to new format.
    'image' -> 'attachment'
    'text_with_image' -> 'text_with_attachment'
    """
    ChatMessage = apps.get_model("chat", "ChatMessage")

    ChatMessage.objects.filter(message_type="image").update(message_type="attachment")
    ChatMessage.objects.filter(message_type="text_with_image").update(
        message_type="text_with_attachment"
    )


def reverse_message_types(apps, schema_editor):
    """
    Reverse message type changes.
    """
    ChatMessage = apps.get_model("chat", "ChatMessage")

    ChatMessage.objects.filter(message_type="attachment").update(message_type="image")
    ChatMessage.objects.filter(message_type="text_with_attachment").update(
        message_type="text_with_image"
    )


def reverse_migrate(apps, schema_editor):
    """
    Reverse migration - no action needed as we're just updating fields.
    """
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        # Step 1: Update ChatMessage message_type choices and data
        migrations.AlterField(
            model_name="chatmessage",
            name="message_type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("attachment", "Attachment"),
                    ("text_with_attachment", "Text with Attachment"),
                ],
                default="text",
                max_length=20,
            ),
        ),
        # Step 2: Update existing message types
        migrations.RunPython(update_message_types, reverse_message_types),
        # Step 3: Rename the model from ChatMessageImage to ChatMessageAttachment
        migrations.RenameModel(
            old_name="ChatMessageImage",
            new_name="ChatMessageAttachment",
        ),
        # Step 4: Rename the table
        migrations.AlterModelTable(
            name="chatmessageattachment",
            table="chat_message_attachments",
        ),
        # Step 5: Rename 'image' field to 'file'
        migrations.RenameField(
            model_name="chatmessageattachment",
            old_name="image",
            new_name="file",
        ),
        # Step 6: Add new fields
        migrations.AddField(
            model_name="chatmessageattachment",
            name="file_type",
            field=models.CharField(
                choices=[("image", "Image"), ("video", "Video")],
                default="image",
                max_length=10,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="chatmessageattachment",
            name="file_name",
            field=models.CharField(
                default="",
                help_text="Original file name",
                max_length=255,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="chatmessageattachment",
            name="file_size",
            field=models.PositiveIntegerField(
                default=0,
                help_text="File size in bytes",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="chatmessageattachment",
            name="duration_seconds",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Duration in seconds for video attachments",
                null=True,
            ),
        ),
        # Step 7: Update the file field to use FileField instead of ImageField
        migrations.AlterField(
            model_name="chatmessageattachment",
            name="file",
            field=models.FileField(upload_to="chat/attachments/%Y/%m/"),
        ),
        # Step 8: Update thumbnail field to allow null
        migrations.AlterField(
            model_name="chatmessageattachment",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                help_text="Thumbnail for video attachments",
                null=True,
                upload_to="chat/thumbnails/%Y/%m/",
            ),
        ),
        # Step 9: Add file_type index
        migrations.AddIndex(
            model_name="chatmessageattachment",
            index=models.Index(fields=["file_type"], name="chat_attach_file_ty_idx"),
        ),
        # Step 10: Update model options
        migrations.AlterModelOptions(
            name="chatmessageattachment",
            options={
                "ordering": ["order"],
                "verbose_name": "Chat Message Attachment",
                "verbose_name_plural": "Chat Message Attachments",
            },
        ),
        # Step 11: Run data migration
        migrations.RunPython(migrate_chatmessageimage_to_attachment, reverse_migrate),
    ]
