# Generated by Django 5.2.7 on 2026-01-16 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatmessageimage_to_chatmessageattachment'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='chatmessageattachment',
            new_name='chat_messag_message_4c3077_idx',
            old_name='chat_messag_message_a5d9c5_idx',
        ),
        migrations.RenameIndex(
            model_name='chatmessageattachment',
            new_name='chat_messag_file_ty_ab3894_idx',
            old_name='chat_attach_file_ty_idx',
        ),
        migrations.AlterField(
            model_name='chatmessageattachment',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='chat.chatmessage'),
        ),
    ]
